name: IaC Full Stack

on:
  push:
    branches:
    - develop
    paths:
    - '.iac/**'

env: 
  dnsZone: 'ryanmcvey.me'
  stackVersion: 'v2'
  stackLocation: 'eastus'
  stackLocationCode: 'us1'
  AppName: 'resume'
  AppBackendName: 'resumecounter'
  tagCostCenter: 'a1b2c3'

jobs:

  deployDevelopment:
    # needs: build
    name: Deploy IaC to development
    environment:
      name: development
      
    env:
      stackEnvironment: 'dev'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.RESUME_GITHUB_V3_SP }}   
    
    - name: Get and Set Subscription Variable
      id: subs
      run: |
        SUBID=$(az account show --query id --output tsv)
        echo "::set-output name=SUBID::${SUBID}"
    - name: Echo SubscriptionId
      run: echo "${{ steps.subs.outputs.subid }}"      
    
    - name: Echo Github.run_id
      id: runId
      run: |
        echo "${{ github.run_id }}"

    - name: Echo Github.run_number
      id: runNumber
      run: |
        echo "${{ github.run_number }}"

    - name: Echo Github.run_attempt
      id: runAttempt
      run: |
        echo "${{ github.run_Attempt }}"
    
    - name: Echo and Set Github Run Link
      id: IACACTIONSLINK
      run: |
        echo "${{ github.server_url }}/${{ github.repository }}/actions/workflows/main-iac.yml"
        IACACTIONSLINK=${{ github.server_url }}/${{ github.repository }}/actions/workflows/main-iac.yml
        echo "::set-output name=IACACTIONSLINK::${IACACTIONSLINK}"
 
    - name: Bicep - Backend
      uses: Azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ steps.subs.outputs.subid }}
        region: ${{env.stackLocation}}
        template: ./.iac/backend-dev.bicep
        parameters: 
                  tagGitActionIacRunId=${{ github.run_id }}
                  tagGitActionIacRunNumber=${{ github.run_number }}
                  tagGitActionIacRunAttempt=${{ github.run_attempt }}
                  tagGitActionIacActionsLink=${{ steps.iacactionslink.outputs.iacactionslink}}
                  tagEnvironmentNameTier=${{env.stackEnvironment}}
                  tagCostCenter=${{env.tagCostCenter}}
                  resourceGroupLocation=${{env.stackLocation}}
                  rgBackendName=${{env.stackLocationCode}}-${{env.AppName}}-be-${{env.stackEnvironment}}-${{env.stackVersion}}-rg
                  cosmosName=${{env.stackLocationCode}}-${{env.AppName}}-${{env.stackEnvironment}}-${{env.stackVersion}}-cmsdb
                  databaseName=azure-resume-click-count
                  containerName=Counter
                  defaultConsistencyLevel=Eventual
                  functionAppStorageAccountName=${{env.stackLocationCode}}${{env.AppBackendName}}${{env.stackEnvironment}}${{env.stackVersion}}sa
                  functionAppAppInsightsName=${{env.stackLocationCode}}-${{env.AppBackendName}}-${{env.stackEnvironment}}-${{env.stackVersion}}-ai
                  functionAppAppServicePlanName=${{env.stackLocationCode}}-${{env.AppBackendName}}-${{env.stackEnvironment}}-${{env.stackVersion}}-asp
                  functionAppName=${{env.stackLocationCode}}-${{env.AppBackendName}}-${{env.stackEnvironment}}-${{env.stackVersion}}-fa
                  functionAppKeySecretNamePrimary=AzureResumeConnectionStringPrimary
                  functionAppKeySecretNameSecondary=AzureResumeConnectionStringSecondary
                  corsFriendlyDnsUri=https://${{env.AppName}}${{env.stackEnvironment}}${{env.stackVersion}}.${{env.dnsZone}}
                  corsCdnUri=https://${{env.stackLocationCode}}-${{env.AppName}}-${{env.stackEnvironment}}-${{env.stackVersion}}-cdn.azureedge.net
                  functionRuntime=dotnet
                  keyVaultName=${{env.stackLocationCode}}-${{env.AppName}}-${{env.stackEnvironment}}-${{env.stackVersion}}-kv
                  keyVaultSku=standard
  
  #                functionName=GetResumeCounter
  
    - name: Bicep - Frontend
      uses: Azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ steps.subs.outputs.subid }}
        region: ${{env.stackLocation}}
        template: ./.iac/frontend-dev.bicep
        parameters: 
                  tagGitActionIacRunId=${{ github.run_id }}
                  tagGitActionIacRunNumber=${{ github.run_number }}
                  tagGitActionIacRunAttempt=${{ github.run_attempt }}
                  tagGitActionIacActionsLink=${{ steps.iacactionslink.outputs.iacactionslink}}
                  tagEnvironmentNameTier=${{env.stackEnvironment}}
                  tagCostCenter=${{env.tagCostCenter}}
                  resourceGroupLocation=${{env.stackLocation}}
                  rgFrontendName=${{env.stackLocationCode}}-${{env.AppName}}-fe-${{env.stackEnvironment}}-${{env.stackVersion}}-rg
                  staticSiteStorageAccountName=${{env.stackLocationCode}}${{env.AppName}}${{env.stackEnvironment}}${{env.stackVersion}}sa
                  staticSiteStorageAccountAppInsightsName=${{env.stackLocationCode}}-${{env.AppName}}-${{env.stackEnvironment}}-${{env.stackVersion}}-ai
    
    - name: Enable Storage Account Frontend Static Website
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob service-properties update --account-name ${{env.stackLocationCode}}${{env.AppName}}${{env.stackEnvironment}}${{env.stackVersion}}sa --auth-mode login --static-website --404-document index.html --index-document index.html

    # - name: Bicep - Frontend CDN and DNS
    #   uses: azure/arm-deploy@v1
    #   with:
    #     scope: subscription
    #     subscriptionId: ${{ steps.subs.outputs.subid }}
    #     region: ${{env.stackLocation}}
    #     template: ./.iac/frontendCdn-dev.bicep
    #     parameters: 
    #               cNameValue=${{env.AppName}}${{env.stackEnvironment}}${{env.stackVersion}}
    #               dnsZoneValue=${{env.dnsZone}}
    #               tagGitActionIacRunId=${{ github.run_id }}
    #               tagGitActionIacRunNumber=${{ github.run_number }}
    #               tagGitActionIacRunAttempt=${{ github.run_attempt }}
    #               tagGitActionIacActionsLink=${{ steps.iacactionslink.outputs.iacactionslink}}
    #               tagEnvironmentNameTier=${{env.stackEnvironment}}
    #               tagCostCenter=${{env.tagCostCenter}}
    #               resourceGroupLocation=${{env.stackLocation}}
    #               rgFrontendName=${{env.stackLocationCode}}-${{env.AppName}}-fe-${{env.stackEnvironment}}-${{env.stackVersion}}-rg
    #               staticSiteStorageAccountName=${{env.stackLocationCode}}${{env.AppName}}${{env.stackEnvironment}}${{env.stackVersion}}sa
    #               staticSiteStorageAccountAppInsightsName=${{env.stackLocationCode}}-${{env.AppName}}-${{env.stackEnvironment}}-${{env.stackVersion}}-ai
    #     failOnStdErr: false 
 
 
 
  # DeployProduction:
  #   needs: deployDevelopment
  #   name: Deploy to production
  #   environment:
  #     name: production
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Download artifacts
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: main-prod
  #   - name: Azure Login
  #     uses: Azure/login@v1.1
  #     with:
  #       creds: ${{ secrets.AZURE_CREDENTIALS }}
  #   - name: get subs
  #     id: subs
  #     run: |
  #       SUBID=$(az account show --query id --output tsv)
  #       echo "::set-output name=SUBID::${SUBID}"
  #   - name: Test
  #     run: echo "${{ steps.subs.outputs.subid }}"
  #   - name: Deploy Azure Resource Manager (ARM) Template
  #     uses: Azure/arm-deploy@v1
  #     with:
  #       scope: subscription
  #       subscriptionId: ${{ steps.subs.outputs.subid }}
  #       region: westeurope
  #       template: main-prod.json
