name: IaC Full Stack
on:
  push:
    branches:
    - develop
    paths:
    - '.iac/**'
    # paths-ignore:
    # - '**/*.md'
  workflow_dispatch:
    branches:
    - develop

jobs:
  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
      # - name: Bicep Build
      #   uses: aliencube/bicep-build-actions@v0.1
      #   with:
      #     files: main-dev.bicep main-prod.bicep
      # - run: ls
      # - run: cat main-dev.json
      # - run: cat main-prod.json
      # - name: Publish Artifacts dev
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: main-dev
      #     path: main-dev.json
      # - name: Publish Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: main-prod
      #     path: main-prod.json
  deployDevelopment:
    # needs: build
    name: Deploy IaC to development
    environment:
      name: development
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    # - name: Download artifacts dev
      # uses: actions/download-artifact@v2
      # with:
      #   name: main-dev
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.RESUME_GITHUB_V3_SP }}   
    - name: get subs
      id: subs
      run: |
        SUBID=$(az account show --query id --output tsv)
        echo "::set-output name=SUBID::${SUBID}"
    - name: Test echo output subId
      run: echo "${{ steps.subs.outputs.subid }}"      
      - name: get runId
      id: runId
      run: |
        echo "::set-output name=runId::${{ env.GITHUB_RUN_ID }}"
    - name: Test echo runId
      run: echo "${{ steps.runId.outputs.runId }}"   
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1
      with:
        scope: subscription
        subscriptionId: ${{ steps.subs.outputs.subid }}
        # subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        region: eastus
        template: ./.iac/main-dev.bicep
        parameters: 
                  resourceGroupLocation=eastus
                  tagEnvironmentNameTier=development
                  tagCostCenter=abc123
                  tagGitActionRunId=${{ env.GITHUB_RUN_ID }}
                  rgBackendName=us1-resume-be-dev-v3-rg
                  rgFrontendName=us1-resume-fe-dev-v3-rg
                  vnetName=vnet-d-eus-001
                  vnetAddressPrefix=12.0.0.0/16
                  subnetName1=snet-d-eus-001-aks-pool01
                  subnetPrefix1=12.0.1.0/24
  # DeployProduction:
  #   needs: deployDevelopment
  #   name: Deploy to production
  #   environment:
  #     name: production
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Download artifacts
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: main-prod
  #   - name: Azure Login
  #     uses: Azure/login@v1.1
  #     with:
  #       creds: ${{ secrets.AZURE_CREDENTIALS }}
  #   - name: get subs
  #     id: subs
  #     run: |
  #       SUBID=$(az account show --query id --output tsv)
  #       echo "::set-output name=SUBID::${SUBID}"
  #   - name: Test
  #     run: echo "${{ steps.subs.outputs.subid }}"
  #   - name: Deploy Azure Resource Manager (ARM) Template
  #     uses: Azure/arm-deploy@v1
  #     with:
  #       scope: subscription
  #       subscriptionId: ${{ steps.subs.outputs.subid }}
  #       region: westeurope
  #       template: main-prod.json
